#include "runtime.c"
typedef int INTEGER;
typedef double REAL;
typedef int BOOLEAN;
typedef STR STRING;
int x = 0;
int a = 0;
int b = 0;
int c = 0;
STR s = {0};
int f = 0;
STR $0 = { .data = "3" };
STR $1 = { .data = "x = " };
STR $2 = { .data = " OK" };
STR $3 = { .data = "f = " };
STR $4 = { .data = "a" };
STR $5 = { .data = "abc" };
STR $6 = { .data = "s = " };
int func(int z)
{
    return z;
}
int main()
{
    x = a;
    const auto $r1 = (a + b);
    x = $r1;
    const auto $r2 = (+a);
    x = $r2;
    const auto $r3 = (-a);
    x = $r3;
    const auto $r5 = (b * c);
    const auto $r4 = (a + $r5);
    x = $r4;
    const auto $r8 = (-b);
    const auto $r9 = (1 - 2);
    const auto $r7 = ($r8 + $r9);
    const auto $r11 = LENGTH($0);
    const auto $r10 = ($r11 * 7);
    const auto $r6 = ($r7 - $r10);
    x = $r6;
    const auto $r14 = (-b);
    const auto $r15 = (1 - 2);
    const auto $r13 = ($r14 + $r15);
    const auto $r16 = func(3);
    const auto $r12 = ($r13 - $r16);
    x = $r12;
    $output("AiA", $1, x, $2);
    const auto $r18 = (a < b);
    const auto $r17 = (!$r18);
    f = $r17;
    const auto $r20 = (a < b);
    const auto $r19 = ($r20 ^ TRUE);
    f = $r19;
    const auto $r22 = (a < b);
    const auto $r24 = (c >= 0);
    const auto $r23 = ($r24 && FALSE);
    const auto $r21 = ($r22 || $r23);
    f = $r21;
    const auto $r27 = (a >= b);
    const auto $r28 = (c < 0);
    const auto $r26 = ($r27 && $r28);
    const auto $r25 = ($r26 || TRUE);
    f = $r25;
    $output("AbA", $3, f, $2);
    const auto $r29 = $concat("ii", a, b);
    s = $r29;
    const auto $r30 = $concat("Ai", $4, b);
    s = $r30;
    const auto $r31 = $concat("Aii", $4, b, c);
    s = $r31;
    const auto $r34 = SUBSTR($5, 0, 2);
    const auto $r33 = $concat("iA", b, $r34);
    const auto $r32 = $concat("iA", a, $r33);
    s = $r32;
    const auto $r36 = SUBSTR($5, 0, 2);
    const auto $r35 = $concat("iiA", a, b, $r36);
    s = $r35;
    const auto $r38 = CHARACTER(b);
    const auto $r37 = $concat("iA", a, $r38);
    s = $r37;
    $output("AAA", $6, s, $2);
}
